#!/usr/bin/env python

import argparse
import os
import subprocess
import sys

def main():
    platform_name = sys.platform
    try:
        package_platform = __import__("package_{}".format(sys.platform))
    except ImportError:
        print "Unknown platform: '{}'".format(platform_name)
        return 1
    
    parser = argparse.ArgumentParser(description="Create a package for ITK")
    try:
        package_platform.setup_parser(parser)
    except Exception, e:
        print e
        return 1
    
    arguments = parser.parse_args()
    
    upstream_version = "4.6.1"
    local_revision = "ipb2"
    
    try:
        package_platform.run(upstream_version, local_revision, **arguments.__dict__)
    except Exception, e:
        print e
        return 1
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
